name: Build executables

on:
  release: 
    types: [published]
  workflow_dispatch:
    

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - run: ls /home/runner/work/clouddns/clouddns/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Release
        path: |
              target/release/clouddns-setup
              target/release/clouddns
